// Code generated by MockGen. DO NOT EDIT.
// Source: fetcher.go
//
// Generated by this command:
//
//	mockgen -source=fetcher.go -destination=mocks/fetcher_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ports "github.com/LerianStudio/matcher/internal/shared/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockFetcherClient is a mock of FetcherClient interface.
type MockFetcherClient struct {
	ctrl     *gomock.Controller
	recorder *MockFetcherClientMockRecorder
	isgomock struct{}
}

// MockFetcherClientMockRecorder is the mock recorder for MockFetcherClient.
type MockFetcherClientMockRecorder struct {
	mock *MockFetcherClient
}

// NewMockFetcherClient creates a new mock instance.
func NewMockFetcherClient(ctrl *gomock.Controller) *MockFetcherClient {
	mock := &MockFetcherClient{ctrl: ctrl}
	mock.recorder = &MockFetcherClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFetcherClient) EXPECT() *MockFetcherClientMockRecorder {
	return m.recorder
}

// GetExtractionJobStatus mocks base method.
func (m *MockFetcherClient) GetExtractionJobStatus(ctx context.Context, jobID string) (*ports.ExtractionJobStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExtractionJobStatus", ctx, jobID)
	ret0, _ := ret[0].(*ports.ExtractionJobStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExtractionJobStatus indicates an expected call of GetExtractionJobStatus.
func (mr *MockFetcherClientMockRecorder) GetExtractionJobStatus(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExtractionJobStatus", reflect.TypeOf((*MockFetcherClient)(nil).GetExtractionJobStatus), ctx, jobID)
}

// GetSchema mocks base method.
func (m *MockFetcherClient) GetSchema(ctx context.Context, connectionID string) (*ports.FetcherSchema, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSchema", ctx, connectionID)
	ret0, _ := ret[0].(*ports.FetcherSchema)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSchema indicates an expected call of GetSchema.
func (mr *MockFetcherClientMockRecorder) GetSchema(ctx, connectionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSchema", reflect.TypeOf((*MockFetcherClient)(nil).GetSchema), ctx, connectionID)
}

// IsHealthy mocks base method.
func (m *MockFetcherClient) IsHealthy(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsHealthy", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsHealthy indicates an expected call of IsHealthy.
func (mr *MockFetcherClientMockRecorder) IsHealthy(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsHealthy", reflect.TypeOf((*MockFetcherClient)(nil).IsHealthy), ctx)
}

// ListConnections mocks base method.
func (m *MockFetcherClient) ListConnections(ctx context.Context, orgID string) ([]*ports.FetcherConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConnections", ctx, orgID)
	ret0, _ := ret[0].([]*ports.FetcherConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConnections indicates an expected call of ListConnections.
func (mr *MockFetcherClientMockRecorder) ListConnections(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConnections", reflect.TypeOf((*MockFetcherClient)(nil).ListConnections), ctx, orgID)
}

// SubmitExtractionJob mocks base method.
func (m *MockFetcherClient) SubmitExtractionJob(ctx context.Context, input ports.ExtractionJobInput) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitExtractionJob", ctx, input)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitExtractionJob indicates an expected call of SubmitExtractionJob.
func (mr *MockFetcherClientMockRecorder) SubmitExtractionJob(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitExtractionJob", reflect.TypeOf((*MockFetcherClient)(nil).SubmitExtractionJob), ctx, input)
}

// TestConnection mocks base method.
func (m *MockFetcherClient) TestConnection(ctx context.Context, connectionID string) (*ports.FetcherTestResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestConnection", ctx, connectionID)
	ret0, _ := ret[0].(*ports.FetcherTestResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TestConnection indicates an expected call of TestConnection.
func (mr *MockFetcherClientMockRecorder) TestConnection(ctx, connectionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestConnection", reflect.TypeOf((*MockFetcherClient)(nil).TestConnection), ctx, connectionID)
}
